### ISSUE TITLE
simple video player example not working

### ISSUE THREAD

**Issue by danimarfil** [fmtvp/talexample#14]
Hello!
I have a TV modulator and I am trying to send my own TV streaming with HbbTV through it. I am using a 2014 Samsung TV and everything is working fine but the video player example. It does not play it through the TV although it does work on Firefox Fire TV Plugin. I have no clue where the problem should be, the only change I have made from this tal example is that I am using another video, but still with h.264 and 960x540px. 
Thanks in advance for your help,

Dani

**Comment by sdclibbery** [comment]
Hi Dani,

Does the talexample work for you unchanged, using the original video?

If that doesn't work either, then I wonder if you are setting a valid 'brand' and 'model' combo in the query parameters from the TV?

Thanks,
Steve

**Comment by danimarfil** [comment]
Hi Steve,
Thanks for your fast answer. Now I am running the app with the original video and it is still not working. I must say that when I press the Exit button on my TV it briefly shows the video until it really stops running the app and then the TV freezes. What do you mean by valid 'brand' and 'model'? I thought it was internally made by every TV that receives the DVB signal. What I have done is uploading the full antie project in order to make it available for every TV that gets that signal. 
Thank you very much again for your reply,

Dani

**Comment by sdclibbery** [comment]
Hi, your Samsung TV probably needs to play media using the Samsung specific media API.

There are a couple of questions in the FAQ (http://fmtvp.github.io/tal/faq.html) that you may find useful, The first is about Samsung support:

Question: Does the TV Application Layer work on Samsung TVs and Blu-ray players?
Answer: TAL is technically able to run on most Samsung devices from 2010 onwards, please contact k.chu@samsung.com for more detailed information.

The second is about the brand/model query parameters:

Question: How does the right device configuration get chosen for each device?
Answer: Internally the BBC has a database that matches device-browser user-agents to device-configuration files (BRAND-MODEL-default.json), but that is not part of what is being shared here. See the SampleApplication for an alternative approach to doing it. The sample application works by specifying the device config file as a URL parameter, but its up to you how you do it.

Does the same app work on other (non Samsung) devices?

**Comment by danimarfil** [comment]
Thank you very much for your answer, 

at the moment I only have a Samsung TV but I am using the Firefox plugin, the Opera TV emulator and the SmartTV Alliance emulator (sdk 4.0). It works fine on every single device but on the SamsungTV. 

I will look further with the information you give me and asap I make it work I will post it here.

Thanks again for your attention

Dani

**Comment by tsadlerBBC** [comment]
Hi Dani,

We're closing this for the time being - if you have any further questions, feel free to reopen this or raise a new issue.

Thanks,

Tom

**Comment by seftonmonk** [comment]
Hi,

Wonder if this is related,

I have checked out your example application and got it running on a amazon fire tv stick pointing to the correct configuration file.

When i go to play a video, the amazon web app crashes with no stack trace, have you guys experienced this, same app works on a chrome perfectly.

Any help would be appreciated.

Cheers,
Sefton
