### ISSUE TITLE
A Question

### ISSUE THREAD

**Issue by sudheeshb** [fmtvp/talexample#4]
Hello,

I  have been going through the TAL frame work to write a re-usable application for Smart TVs.  I could write and test application in PC, but couldn't get enough information on how to port the application actually into a device say for example Samsung Start TV 2013 models.

I tried to contact Samsung ( as per the TAL FAQ ) to get more information about this. Couldn't succeed yet.

Can you please provide more information on this?.  I couldn't find a better place/e-mail id to post this question.

**Comment by navneetdixit07** [comment]
I have downloaded the sample code which has index.php with TAL framework(Antie).
I am able to run on the browser.
Is there any way I can run this code on tv simulator/emulator?
