### ISSUE TITLE
Carousel focus breaks when datasource is asychronous

### ISSUE THREAD

**Issue by ryanbeard** [fmtvp/talexample#8]
I'm just getting to grips with the TAL framework, and as part of this I'm making modifications and additions to the TAL example. One change I made immediately was to update the simplefeed datasource into an ajax request for the same data (you can also mock this by wrapping the callbacks.onSuccess call in a setTimeout). Whilst the data came through and rendered in the carousel, it no longer gained focus. Focus was still on the previous component (simple.js).

Please can you tell me what needs doing to the example to handle asynchronous data, as I've tried lots of different things without any success. I'm not sure if this is a bug or an implementation oddity, but any help/advice would be much appreciated. Thanks.

Example simplefeed.js file here: https://gist.github.com/ryanbeard/8705597

Update: I have managed to force the focus to appear on the carousel item by binding to the databound event of the datasource and explicitly setting focus:
```
this._carousel.addEventListener("databound", function(evt) {
    self._carousel.getActiveChildWidget().focus();
});
```
...but when we click a fruit item and return back to the home screen, focus is again lost. This seems to be the only thing that *nearly* works. I have tried various ways of trying to force the focus, e.g.
```
self.setActiveChild(self._carousel);
```
```
self._carousel.setActiveChild(self._carousel.getActiveChild());
```
```
self._carousel.setActiveChild(self._carousel._childWidgetOrder[0]);
```
...etc without any luck.

**Comment by sanderlooijenga** [comment]
You could very simply (next to setting `focus` on the `carousel` in the `databound` event listener) add another event listener on `beforeshow` and then do something like this:

`
var self = this;

this.addEventListener('beforeshow', function (evt) {
    if (evt.args.fromBack === true) {
        self._carousel.focus();
    }
});
`

**Comment by tsadlerBBC** [comment]
Closing this issue for now. Please reopen if you have any improved workarounds. Keep your eye on TAL and TAL example for any improvements we might do in this area.
